from fastapi import APIRouter
from fastapi.responses import RedirectResponse

root_api = APIRouter(tags=['Root'])


@root_api.get("/", summary="Root")
async def root():
    return {"message": "Root - VITA: Visionary Industrial Technology Architecture"}


@root_api.get('/html/docs', summary="Root")
async def html_docs():
    """
    Redirects to the HTML documentation generated by Sphinx.
    Make sure the HTTP server is running inside `/docs/build/html/`.
    Example to start the server:
        cd docs
        make clean
        make html
    """
    docs_url = "http://127.0.0.1:8000/html/docs/"  # ou URL pública na VPS
    return RedirectResponse(url=docs_url)