version: "3.9"

services:
  vita-api:
    container_name: vita-api
    build: .

    ports:
      - "8000:8000"

    environment:
      - DOCKER=true
      - TZ=America/Sao_Paulo

    volumes:
      - ./:/app

    restart: always

    logging:
      options:
        max-size: "100m"

    mem_limit: 4g